### ISSUE TITLE
 puppet npm module not supported: "wechaty-puppet-xp"

### ISSUE THREAD

**Issue by 865881900** [wechaty/wechaty-puppet-xp#15]
/wechaty/src/puppet-manager.ts:123:13  源码中的这段代码中的 PUPPET_DEPENDENCIES 没有 wechaty-puppet-xp 这个属相,

```ts
if (!(puppetName in PUPPET_DEPENDENCIES)) {
      throw new Error(
        [
          '',
          'puppet npm module not supported: "' + puppetName + '"',
          'learn more about supported Wechaty Puppet from our directory at',
          '<https://github.com/wechaty/wechaty-puppet/wiki/Directory>',
          '',
        ].join('\n')
      )
    }
```

**Comment by huan** [comment]
Please use the latest version of Wechaty, it should works as expected.

For example, follow

**Comment by 865881900** [comment]
> 请使用最新版本的微信，它应该可以正常工作。
> 
> 例如关注https://github.com/wechaty/wechaty-getting-started

Ok, thank you;

**Comment by huan** [comment]
You are welcome. 

Please close this issue if you can confirm it works for you, or let me know if you need more help.

Good luck!
