### ISSUE TITLE
Feature request: get the nickname of non-friends

### ISSUE THREAD

**Issue by 865881900** [wechaty/wechaty-puppet-xp#18]
Excuse me, in the group chat, how can I get the nickname of non-friends?

**Comment by atorber** [comment]
This feature is not supported yet, but it will be solved soon. 
Thank you for your attention，we will reply this issue  as soon as the it is ready.

**Comment by 865881900** [comment]
ok,thank you;

**Comment by huan** [comment]
I'd like to suggest that we should keep this issue to be open so that we can track this feature request.

**Comment by atorber** [comment]
@865881900 This feature is already supported in the latest version.

**Comment by 865881900** [comment]
ok hard

**Comment by 865881900** [comment]
> @865881900最新版本已支持此功能。

You were laborious
