### ISSUE TITLE
向机器人发送 ding 没有得到 dong回复

### ISSUE THREAD

**Issue by atorber** [wechaty/wechaty-puppet-xp#8]
向机器人发送 ding 没有得到 dong回复，返回如下错误

10:26:42 VERB SidecarBody [HOOK_EVENT_HANDLER]("{"args":{"0":1,"1":"tyutluyc","2":"ding","3":null,"4":"<msgsource />\n"},"method":"recvMsg"}")
recvMsg: {
  '0': 1,
  '1': 'tyutluyc',
  '2': 'ding',
  '3': null,
  '4': '<msgsource />\n'
}
recvMsg: talkerId = tyutluyc
recvMsg: text = ding
recvMsg: ding found, reply dong
10:26:42 VERB WeChatSidecar<Sidecar> sendMsg(tyutluyc, dong)
10:26:42 SILL SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]({"type":"send","payload":{"payload":{"level":"verbose","message":"sendMsg(tyutluyc, dong)","prefix":"SidecarAgent"},"type":"log"}}, null)
10:26:42 SILL SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Send: {"payload":{"level":"verbose","message":"sendMsg(tyutluyc, dong)","prefix":"SidecarAgent"},"type":"log"}
10:26:42 VERB SidecarBody<SidecarAgent> sendMsg(tyutluyc, dong)
(node:6692) UnhandledPromiseRejectionWarning: TypeError: not a function
    at sendMsg (/script1.js:472)
    at <anonymous> (/script1.js:511)
    at __sidecar__sendMsg_Function_wrapper (/script1.js:628)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)
(node:6692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by huan** [comment]
Thanks for filing the issue, this problem has been confirmed and will be investigated later.

**Comment by huan** [comment]
Thanks for filing the issue, this problem has been confirmed and will be investigated later.
